#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

python manage.py lint
LINT=$?
#python manage.py test
#TEST=$?

if [ "$LINT" -ne "1" ]; then
    echo "Lint error, not committing"
    exit 1
fi

#if [ "$TEST" -ne "1" ]; then
#    echo "Test error, not committing"
#    exit 1
#fi

